// Practice content library. Plain data; Speech Tracker Dev can add more anytime.
const PROMPTS={
twisters:["Red leather, yellow leather — 10 times, faster each round.","Unique New York, you know you need unique New York.","She sells seashells by the seashore.","Peter Piper picked a peck of pickled peppers.","The sixth sick sheikh's sixth sheep's sick.","Specific Pacific — say it 10 times, crisp final C.","Toy boat, toy boat, toy boat (keep every T clear).","Irish wristwatch, Swiss wristwatch.","Fresh French fried fish.","Rubber baby buggy bumpers.","A proper copper coffee pot.","Truly rural, truly rural, truly rural."],
warmups:["Slow belly breaths: in 4, hold 4, out 6 — five rounds.","Lip trills (brrr) up and down your range for 30 seconds.","Hum 'mmm' and feel the buzz in your lips and nose, then open to 'mmm-ah'.","Big jaw stretches and tongue circles, 10 each way.","Say the vowels slowly and over-shaped: A — E — I — O — U."],
diction:["Read a paragraph aloud with a pen (or finger) lightly between your teeth, then read it again normally. Notice how much clearer it is.","Over-articulate every final consonant in a paragraph: T, D, K, P, S.","Read a paragraph at half speed, pausing at every comma and period.","Read the same paragraph three times: slow, normal, then fast — stay clear at every speed.","Pick 5 words you tend to mumble and say each 5 times slowly, then in a sentence."],
reading:["Read a news article aloud for the full block, as if presenting it to your team.","Read a page from a business or leadership book aloud. Underline any word you don't know.","Read an email or report from work aloud as if you're presenting it in a meeting.","Read a famous speech aloud (MLK, JFK, Steve Jobs at Stanford). Copy the pauses and emphasis."],
topics:["Explain what you do at work to someone outside your field in 60 seconds.","Give a 2-minute update on your current project to a senior leader.","Why should you be promoted? Make the case in 90 seconds, with three reasons and an example.","Describe a problem you solved recently: situation, action, result.","Disagree politely with a decision, and propose an alternative.","Introduce yourself at a leadership meeting in 45 seconds.","Explain a mistake you made and what you learned from it.","Teach someone a skill you're good at, in 2 minutes.","Pitch an idea that would save your team time.","Give feedback to a coworker kindly but clearly.","Summarize this week's biggest news in 1 minute.","Tell a short story from your childhood with a clear beginning, middle, and end.","Answer: 'Where do you see yourself in 3 years?'","Run a 2-minute mock meeting opening: the goal, the agenda, and the decision needed.","Thank your team for a big win, in 60 seconds.","Explain a number or chart to someone who hates numbers.","Handle a tough question: 'Why is this project late?'","Describe your ideal team and how you'd lead it.","Convince a skeptic to try your favorite tool or habit.","Give a 1-minute toast at a coworker's farewell."],
storytelling:["Tell the story of your career so far in 3 minutes, as a story with a turning point.","Retell a movie plot in 2 minutes with suspense and pauses.","Tell a story about a time you led without the title."],
review:["Play back your recording. Count your filler words (um, uh, like, you know).","Listen for one word you rushed or swallowed. Say it 5 times clearly.","Rate yourself honestly below and write one thing to fix next time."],
words:[["articulate","express clearly and effectively"],["concise","brief but complete"],["pragmatic","practical, focused on what works"],["leverage","use something to maximum advantage"],["mitigate","make less severe"],["prioritize","decide what matters most first"],["candid","honest and direct"],["cohesive","forming a united whole"],["diligent","careful and hard-working"],["eloquent","fluent and persuasive in speaking"],["facilitate","make an action or process easier"],["meticulous","showing great attention to detail"],["proactive","acting ahead of problems"],["resilient","able to recover quickly"],["succinct","clearly expressed in few words"],["tangible","clear and definite; real"],["ubiquitous","found everywhere"],["viable","capable of working successfully"],["advocate","publicly support or recommend"],["alleviate","make suffering or a problem less"],["ambiguous","open to more than one meaning"],["catalyst","something that speeds up change"],["consensus","general agreement"],["delegate","give a task to someone else"],["discern","recognize or judge well"],["empathy","understanding others' feelings"],["foster","encourage the development of"],["holistic","looking at the whole system"],["impeccable","flawless"],["incentivize","motivate with a reward"],["initiative","the ability to act without being told"],["integrity","being honest and having strong principles"],["juxtapose","place side by side to compare"],["lucid","clear and easy to understand"],["nuance","a subtle difference in meaning"],["optimize","make as effective as possible"],["paradigm","a typical model or pattern"],["persuasive","good at convincing"],["quantify","express as a number"],["rapport","a friendly, understanding relationship"],["rationale","the reasons for a decision"],["scalable","able to grow without breaking"],["streamline","make more efficient"],["synthesize","combine into a coherent whole"],["transparent","open, easy to see through"],["unequivocal","leaving no doubt"],["validate","confirm something is correct"],["versatile","able to adapt to many tasks"],["accountable","responsible for results"],["benchmark","a standard to measure against"],["collaborate","work jointly with others"],["contingency","a plan for a possible event"],["deliberate","done intentionally; or to think carefully"],["expedite","speed up"],["feasible","possible to do"],["galvanize","inspire to action"],["inherent","existing as a natural part"],["insightful","showing deep understanding"],["mentor","an experienced adviser"],["poise","calm, confident composure"]]
};
// Session plans: minutes per block. Total matches the session length.
const PLANS={
30:[["warmup",5],["diction",5],["vocab",7],["speak",8],["review",5]],
60:[["warmup",8],["diction",10],["vocab",12],["reading",10],["speak",12],["review",8]],
120:[["warmup",10],["diction",15],["vocab",20],["reading",20],["speak",25],["story",15],["review",15]]
};
